[package]
name = "grp2p"
version = "0.0.1"
authors = ["Giannis Rovithakis <giannis.rovithakis@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/grp2p.rs"

[dependencies.elrond-wasm]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"
